#!/usr/bin/env perl
use strict;
use warnings;

my @rho = (
    [0, 36, 3, 41, 18],
    [1, 44, 10, 45, 2],
    [62, 6, 43, 15, 61],
    [28, 55, 25, 21, 56],
    [27, 20, 39, 8, 14],
);

sub phys {
    my ($power, $x, $y) = @_;
    for (1 .. $power) {
        $y = ($x + 2 * $y) % 5;
    }
    return $x + 5 * $y;
}

sub xr { return '%xmm' . $_[0]; }
sub ins { print "    $_[0]\n"; }

sub chi_imm {
    my ($dest_role, $src1_role, $src2_role) = @_;
    my $imm = 0;
    for my $index (0 .. 7) {
        my @role;
        $role[$dest_role] = ($index >> 2) & 1;
        $role[$src1_role] = ($index >> 1) & 1;
        $role[$src2_role] = $index & 1;
        my $out = $role[0] ^ ((1 ^ $role[1]) & $role[2]);
        $imm |= $out << $index;
    }
    return $imm;
}

sub emit_round {
    my ($i) = @_;
    print "\n    # Round mapping N^$i -> N^" . ($i + 1) . ".\n";
    for my $x (0 .. 4) {
        my @p = map { phys($i, $x, $_) } 0 .. 4;
        ins(sprintf("vmovdqa64 %7s, %s", xr($p[0]), xr(25 + $x)));
        ins(sprintf("vpternlogq \$0x96, %7s, %7s, %s",
                    xr($p[2]), xr($p[1]), xr(25 + $x)));
        ins(sprintf("vpternlogq \$0x96, %7s, %7s, %s",
                    xr($p[4]), xr($p[3]), xr(25 + $x)));
    }
    for my $x (0 .. 4) {
        my $prev = 25 + (($x + 4) % 5);
        my $next = 25 + (($x + 1) % 5);
        ins(sprintf("vprolq \$1, %s, %%xmm30", xr($next)));
        for my $y (0 .. 4) {
            my $p = phys($i, $x, $y);
            ins(sprintf("vpternlogq \$0x96, %%xmm30, %s, %s",
                        xr($prev), xr($p)));
        }
    }
    for my $y (0 .. 4) {
        my $shift = (2 * $y) % 5;
        my @orders = (
            [0, 1, 2, 3, 4],
            [0, 1, 3, 2, 4],
            [0, 1, 4, 3, 2],
            [0, 1, 2, 4, 3],
            [0, 1, 2, 3, 4],
        );
        my @order = @{$orders[$shift]};
        my %position;
        $position{$order[$_]} = $_ for 0 .. 4;
        my %location;
        for my $b (0 .. 4) {
            my $source_x = ($b - $shift + 5) % 5;
            $location{$b} = phys($i + 1, $source_x, $y);
        }

        print "\n    # Output plane y=$y, B shift=$shift.\n";
        for my $x (0 .. 4) {
            my $p = phys($i + 1, $x, $y);
            my $logical_y = ($x + 2 * $y) % 5;
            my $rot = $rho[$x][$logical_y];
            ins(sprintf("vprolq \$%d, %s, %s", $rot, xr($p), xr($p)))
                if $rot;
        }

        my $next_temp = 25;
        for my $step (0 .. 4) {
            my $x = $order[$step];
            my $dest = phys($i + 1, $x, $y);
            my $old_b = ($x + $shift) % 5;
            my @users = ($old_b, ($old_b + 4) % 5, ($old_b + 3) % 5);
            my $last_use = 0;
            for my $user (@users) {
                $last_use = $position{$user}
                    if $position{$user} > $last_use;
            }
            if ($step < $last_use) {
                ins(sprintf("vmovdqa64 %s, %s",
                            xr($dest), xr($next_temp)));
                $location{$old_b} = $next_temp++;
            }

            my @needed = ($x, ($x + 1) % 5, ($x + 2) % 5);
            my $dest_role = -1;
            for my $role (0 .. 2) {
                $dest_role = $role if $needed[$role] == $old_b;
            }
            if ($dest_role < 0) {
                ins(sprintf("vmovdqa64 %s, %s",
                            xr($location{$needed[0]}), xr($dest)));
                $dest_role = 0;
            }
            my @source_roles = grep { $_ != $dest_role } 0 .. 2;
            my ($src1_role, $src2_role) = @source_roles;
            my $imm = chi_imm($dest_role, $src1_role, $src2_role);
            ins(sprintf("vpternlogq \$0x%02X, %s, %s, %s", $imm,
                        xr($location{$needed[$src2_role]}),
                        xr($location{$needed[$src1_role]}), xr($dest)));
            delete $location{$old_b}
                if exists($location{$old_b}) && $location{$old_b} == $dest;
        }
    }
    ins(sprintf("vmovq %d(%%r14), %%xmm31", 8 * $i));
    ins("vpxorq %xmm31, %xmm0, %xmm0");
}

print <<'ASM';
# BEGIN GENERATED BY scripts/gen_keccak_inplace4.pl
# Fixed-shape H(pk) core using Keccak Team Algorithm 4.
# N(x,y)=(x,x+2y) mod 5 has order four, so each group returns the state to
# canonical order without the compact core's per-round 25-register reorder.
# xmm0-xmm24 hold lanes and xmm25-xmm31 are temporary registers.
.type .Lmlkem_keccakf1600_avx512vl_inplace4_permute,@function
.balign 32
.Lmlkem_keccakf1600_avx512vl_inplace4_permute:
    movl $6, %r13d
    leaq .Lmlkem_sha3_256_rc(%rip), %r14
.balign 32
.Lmlkem_keccakf1600_avx512vl_inplace4_group:
ASM

emit_round($_) for 0 .. 3;

print <<'ASM';
    addq $32, %r14
    decl %r13d
    jnz .Lmlkem_keccakf1600_avx512vl_inplace4_group
    ret
.size .Lmlkem_keccakf1600_avx512vl_inplace4_permute,.-.Lmlkem_keccakf1600_avx512vl_inplace4_permute
# END GENERATED BY scripts/gen_keccak_inplace4.pl

ASM
